spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app
spring.datasource.username=postgres
spring.datasource.password=9999

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt-secret=045ddeb7f631b771488698c829dba97f89222ddf764dfc7d451c0f5653903ab4
app.jwt-expiration-milliseconds=604800000
