spring.application.name=app
spring.datasource.url=jdbc:postgresql://localhost:5432/banking_app
spring.datasource.username=postgres
spring.datasource.password=9999

spring.jpa.hibernate.ddl-auto = update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt-secret=d7108cda683ea212eaa9c4a7480b9c1fc2cd969fdb84f22016dc1c59a72885df
app.jwt-expiration-milliseconds=604800000
